import { ExerciseInfo, WorkoutSession } from "../../stores/workout/types";

export const username = "Pencil Neck";

export const defaultSession: WorkoutSession = {
  id: Date.now().toString(),
  name: `${new Date().toLocaleDateString(
    "en-GB"
  )} - ${new Date().toLocaleTimeString("en-GB", {
    hour: "2-digit",
    minute: "2-digit",
  })}`,
  // e.g. "07/10/2025 10:00"
  startTime: new Date().toISOString(),
  isActive: false,
  layout: [],
  createdAt: new Date().toISOString(),
};

export const bodyPartsTemplate = {
  chest: ["upper chest", "mid chest", "lower chest"],
  shoulders: ["front delts", "side delts", "rear delts"],
  back: ["lats", "lower back", "upper traps", "mid traps", "rear delts"],
  arms: ["biceps", "brachialis", "triceps", "forearms"],
  legs: ["quads", "hamstrings", "glutes", "calves", "adductors"],
  core: ["abs", "obliques", "hip flexors"],
  fullBody: ["forearms", "grip", "core", "legs", "shoulders"],
};

export const equipmentTemplate = [
  "barbell",
  "dumbbells",
  "bench",
  "rack",
  "cable",
  "bodyweight",
  "dip bar",
  "pull-up bar",
  "machine", // generic gym machines
  "box",
  "kettlebell",
  "ab wheel",
  "preacher bench",
];

export const exercisesDefList: ExerciseInfo[] = [
  {
    id: "ex-bench-press",
    slug: "bench-press",
    defaultName: "Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["triceps", "front delts", "side delts"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-back-squat",
    slug: "back-squat",
    defaultName: "Barbell Back Squat",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "rack"],
  },
  {
    id: "ex-deadlift",
    slug: "deadlift",
    defaultName: "Conventional Deadlift",
    category: "back",
    primaryMuscles: ["hamstrings", "glutes", "lower back"],
    secondaryMuscles: ["mid traps", "forearms"],
    equipment: ["barbell"],
  },
  {
    id: "ex-ohp",
    slug: "ohp",
    defaultName: "Overhead Press",
    category: "shoulders",
    primaryMuscles: ["front delts", "side delts"],
    secondaryMuscles: ["triceps", "rear delts"],
    equipment: ["barbell"],
  },
  {
    id: "ex-pullups",
    slug: "pullups",
    defaultName: "Pull Up",
    category: "back",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "rear delts"],
    equipment: ["bodyweight", "pull-up-bar"],
  },
  {
    id: "ex-incline-bench",
    slug: "incline-bench",
    defaultName: "Incline Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["triceps", "front delts"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-decline-bench",
    slug: "decline-bench",
    defaultName: "Decline Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["lower chest"],
    secondaryMuscles: ["triceps", "front delts"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-db-bench",
    slug: "db-bench",
    defaultName: "Dumbbell Bench Press",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["triceps", "front delts", "side delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-db-incline",
    slug: "db-incline",
    defaultName: "Incline Dumbbell Press",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["triceps", "front delts", "side delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-dips",
    slug: "dips",
    defaultName: "Weighted Dips",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["triceps", "front delts"],
    equipment: ["bodyweight", "dip-bar"],
  },
  {
    id: "ex-leg-press",
    slug: "leg-press",
    defaultName: "Leg Press",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
  },
  {
    id: "ex-leg-ext",
    slug: "leg-ext",
    defaultName: "Leg Extension",
    category: "legs",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-leg-curl",
    slug: "leg-curl",
    defaultName: "Leg Curl",
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-barbell-lunge",
    slug: "barbell-lunge",
    defaultName: "Barbell Lunge",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell"],
  },
  {
    id: "ex-rdl",
    slug: "rdl",
    defaultName: "Romanian Deadlift",
    category: "back",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    equipment: ["barbell"],
  },
  {
    id: "ex-barbell-row",
    slug: "barbell-row",
    defaultName: "Barbell Bent-Over Row",
    category: "back",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps", "mid traps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-1arm-db-row",
    slug: "1arm-db-row",
    defaultName: "One-Arm Dumbbell Row",
    category: "back",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-lat-pulldown",
    slug: "lat-pulldown",
    defaultName: "Lat Pulldown",
    category: "back",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
  },
  {
    id: "ex-cable-row",
    slug: "cable-row",
    defaultName: "Seated Cable Row",
    category: "back",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
  },
  {
    id: "ex-barbell-shrug",
    slug: "barbell-shrug",
    defaultName: "Barbell Shrug",
    category: "shoulders",
    primaryMuscles: ["upper traps", "mid traps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-lateral-raise",
    slug: "lateral-raise",
    defaultName: "Dumbbell Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["side delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-front-raise",
    slug: "front-raise",
    defaultName: "Front Dumbbell Raise",
    category: "shoulders",
    primaryMuscles: ["front delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-rear-delt-fly",
    slug: "rear-delt-fly",
    defaultName: "Rear Delt Fly",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["mid traps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-barbell-curl",
    slug: "barbell-curl",
    defaultName: "Barbell Bicep Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-hammer-curl",
    slug: "hammer-curl",
    defaultName: "Hammer Curl",
    category: "arms",
    primaryMuscles: ["biceps", "brachialis"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-tricep-pushdown",
    slug: "tricep-pushdown",
    defaultName: "Tricep Pushdown",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-oh-tricep-ext",
    slug: "oh-tricep-ext",
    defaultName: "Overhead Tricep Extension",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "cable"],
  },
  {
    id: "ex-ab-wheel",
    slug: "ab-wheel",
    defaultName: "Ab Wheel Rollout",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["ab-wheel"],
  },
  {
    id: "ex-cable-crunch",
    slug: "cable-crunch",
    defaultName: "Cable Crunch",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-hanging-leg-raise",
    slug: "hanging-leg-raise",
    defaultName: "Hanging Leg Raise",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["pull-up-bar"],
  },
  {
    id: "ex-bb-glute-bridge",
    slug: "bb-glute-bridge",
    defaultName: "Barbell Glute Bridge",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell"],
  },
  {
    id: "ex-hip-thrust",
    slug: "hip-thrust",
    defaultName: "Hip Thrust",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-seated-leg-curl",
    slug: "seated-leg-curl",
    defaultName: "Seated Leg Curl",
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-good-morning",
    slug: "good-morning",
    defaultName: "Good Morning",
    category: "back",
    primaryMuscles: ["hamstrings", "lower back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-sldl",
    slug: "sldl",
    defaultName: "Stiff-Legged Deadlift",
    category: "back",
    primaryMuscles: ["hamstrings", "lower back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-sumo-deadlift",
    slug: "sumo-deadlift",
    defaultName: "Sumo Deadlift",
    category: "back",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["quads", "lower back"],
    equipment: ["barbell"],
  },
  {
    id: "ex-concentration-curl",
    slug: "concentration-curl",
    defaultName: "Concentration Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
  },
  {
    id: "ex-preacher-curl",
    slug: "preacher-curl",
    defaultName: "Preacher Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "preacher-bench"],
  },
  {
    id: "ex-incline-bicep-curl",
    slug: "incline-bicep-curl",
    defaultName: "Incline Dumbbell Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-db-tricep-kickback",
    slug: "db-tricep-kickback",
    defaultName: "Dumbbell Tricep Kickback",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-skullcrusher",
    slug: "skullcrusher",
    defaultName: "Skullcrusher",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-cable-lateral",
    slug: "cable-lateral",
    defaultName: "Cable Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["side delts"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-arnold-press",
    slug: "arnold-press",
    defaultName: "Arnold Press",
    category: "shoulders",
    primaryMuscles: ["front delts", "side delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-db-rear-delt-row",
    slug: "db-rear-delt-row",
    defaultName: "Dumbbell Rear Delt Row",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["mid traps", "lats"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-cable-rear-delt",
    slug: "cable-rear-delt",
    defaultName: "Cable Rear Delt Fly",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["mid traps"],
    equipment: ["cable"],
  },
  {
    id: "ex-pec-deck",
    slug: "pec-deck",
    defaultName: "Pec Deck Fly",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["machine"],
  },
  {
    id: "ex-cable-fly",
    slug: "cable-fly",
    defaultName: "Cable Fly",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-db-fly",
    slug: "db-fly",
    defaultName: "Dumbbell Fly",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-incline-db-fly",
    slug: "incline-db-fly",
    defaultName: "Incline Dumbbell Fly",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-cable-crossover",
    slug: "cable-crossover",
    defaultName: "Cable Cross Over",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-squat-jump",
    slug: "squat-jump",
    defaultName: "Bodyweight Squat Jump",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bodyweight"],
  },
  {
    id: "ex-calf-raise",
    slug: "calf-raise",
    defaultName: "Standing Calf Raise",
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine", "bodyweight"],
  },
  {
    id: "ex-seated-calf-raise",
    slug: "seated-calf-raise",
    defaultName: "Seated Calf Raise",
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-farmer-carry",
    slug: "farmer-carry",
    defaultName: "Farmer Carry",
    category: "fullBody",
    primaryMuscles: ["forearms", "grip", "core"],
    secondaryMuscles: ["legs", "front delts", "side delts"],
    equipment: ["dumbbells", "barbells"],
  },
  {
    id: "ex-kettlebell-swing",
    slug: "kettlebell-swing",
    defaultName: "Kettlebell Swing",
    category: "posterior-chain",
    primaryMuscles: ["glutes", "hamstrings", "lower back"],
    secondaryMuscles: ["side delts", "front delts", "core"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-cable-woodchopper",
    slug: "cable-woodchopper",
    defaultName: "Cable Woodchopper",
    category: "core",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs", "side delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-bb-hip-thrust",
    slug: "bb-hip-thrust",
    defaultName: "Barbell Hip Thrust",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-db-step-up",
    slug: "db-step-up",
    defaultName: "Dumbbell Step-Up",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["dumbbells", "box"],
  },
  {
    id: "ex-cable-lat-raise",
    slug: "cable-lat-raise",
    defaultName: "Cable Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["side delts"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-face-pull",
    slug: "face-pull",
    defaultName: "Cable Face Pull",
    category: "back",
    primaryMuscles: ["rear delts", "mid traps"],
    secondaryMuscles: ["lats", "side delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-deadstop-row",
    slug: "deadstop-row",
    defaultName: "Barbell Deadstop Row",
    category: "back",
    primaryMuscles: ["lats", "mid traps"],
    secondaryMuscles: ["rear delts", "biceps"],
    equipment: ["barbell", "rack"],
  },
  {
    id: "ex-bb-goodmorning",
    slug: "bb-goodmorning",
    defaultName: "Barbell Good Morning",
    category: "back",
    primaryMuscles: ["lower back", "hamstrings"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-oh-cable-tricep",
    slug: "oh-cable-tricep",
    defaultName: "Standing Overhead Cable Tricep Extension",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-db-lateral-lunge",
    slug: "db-lateral-lunge",
    defaultName: "Dumbbell Lateral Lunge",
    category: "legs",
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-bb-shrug-behind",
    slug: "bb-shrug-behind",
    defaultName: "Barbell Behind-the-Back Shrug",
    category: "back",
    primaryMuscles: ["upper traps"],
    secondaryMuscles: ["mid traps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-machine-row",
    slug: "machine-row",
    defaultName: "Machine Row",
    category: "back",
    primaryMuscles: ["lats", "mid traps"],
    secondaryMuscles: ["rear delts", "biceps"],
    equipment: ["machine"],
  },
  {
    id: "ex-machine-chest-press",
    slug: "machine-chest-press",
    defaultName: "Machine Chest Press",
    category: "chest",
    primaryMuscles: ["mid chest"],
    secondaryMuscles: ["front delts", "triceps"],
    equipment: ["machine"],
  },
  {
    id: "ex-incline-cable-fly",
    slug: "incline-cable-fly",
    defaultName: "Incline Cable Fly",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-low-cable-crossover",
    slug: "low-cable-crossover",
    defaultName: "Low Cable Crossover",
    category: "chest",
    primaryMuscles: ["lower chest"],
    secondaryMuscles: ["front delts", "side delts"],
    equipment: ["cable"],
  },
];
