import {
  ExerciseInfo,
  SessionLayoutItem,
  WorkoutSession,
} from "../../stores/workout/types";

export const username = "Pencil Neck";

export const defaultSession: WorkoutSession = {
  id: Date.now().toString(),
  name: `Workout ${new Date().toLocaleDateString("en-GB")}`, // e.g. "07/10/2025"
  startTime: new Date().toISOString(),
  isActive: false,
  layout: [],
  createdAt: new Date().toISOString(),
};

export const exerciseLibrary: ExerciseInfo[] = [
  {
    id: "ex-bench-press",
    slug: "bench-press",
    defaultName: "Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    metadata: { difficulty: "intermediate" },
  },
  {
    id: "ex-squat",
    slug: "back-squat",
    defaultName: "Barbell Back Squat",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "rack"],
    metadata: { difficulty: "intermediate" },
  },
  {
    id: "ex-deadlift",
    slug: "deadlift",
    defaultName: "Conventional Deadlift",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back", "traps"],
    equipment: ["barbell"],
    metadata: { difficulty: "advanced" },
  },
  {
    id: "ex-shoulder-press",
    slug: "ohp",
    defaultName: "Overhead Press",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-pullups",
    slug: "pullups",
    defaultName: "Pull-Ups",
    category: "pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight"],
  },
  // --- EXTENDED EXERCISES START HERE ---
  {
    id: "ex-incline-bench",
    slug: "incline-bench",
    defaultName: "Incline Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    metadata: { difficulty: "intermediate" },
  },
  {
    id: "ex-decline-bench",
    slug: "decline-bench",
    defaultName: "Decline Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["lower chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    metadata: { difficulty: "intermediate" },
  },
  {
    id: "ex-dumbbell-bench",
    slug: "db-bench",
    defaultName: "Dumbbell Bench Press",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-dumbbell-incline",
    slug: "db-incline",
    defaultName: "Incline Dumbbell Press",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-dips",
    slug: "dips",
    defaultName: "Weighted Dips",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["bodyweight", "dip bar"],
  },
  {
    id: "ex-leg-press",
    slug: "leg-press",
    defaultName: "Leg Press",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["leg press machine"],
  },
  {
    id: "ex-leg-extension",
    slug: "leg-ext",
    defaultName: "Leg Extension",
    category: "legs",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["leg extension machine"],
    metadata: { difficulty: "beginner" },
  },
  {
    id: "ex-leg-curl",
    slug: "leg-curl",
    defaultName: "Leg Curl",
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["leg curl machine"],
  },
  {
    id: "ex-lunge",
    slug: "barbell-lunge",
    defaultName: "Barbell Lunge",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell"],
  },
  {
    id: "ex-romanian-deadlift",
    slug: "rdl",
    defaultName: "Romanian Deadlift",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    equipment: ["barbell"],
  },
  {
    id: "ex-bent-over-row",
    slug: "barbell-row",
    defaultName: "Barbell Bent-Over Row",
    category: "pull",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps", "traps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-one-arm-dumbbell-row",
    slug: "1arm-db-row",
    defaultName: "One-Arm Dumbbell Row",
    category: "pull",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
  },
  {
    id: "ex-lat-pulldown",
    slug: "lat-pulldown",
    defaultName: "Lat Pulldown",
    category: "pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-seated-cable-row",
    slug: "cable-row",
    defaultName: "Seated Cable Row",
    category: "pull",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-shrug",
    slug: "barbell-shrug",
    defaultName: "Barbell Shrug",
    category: "shoulders",
    primaryMuscles: ["traps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-lateral-raise",
    slug: "lateral-raise",
    defaultName: "Dumbbell Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-front-raise",
    slug: "front-raise",
    defaultName: "Front Dumbbell Raise",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-rear-delt-fly",
    slug: "rear-delt-fly",
    defaultName: "Rear Delt Fly",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["traps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-bicep-curl",
    slug: "barbell-curl",
    defaultName: "Barbell Bicep Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-hammer-curl",
    slug: "hammer-curl",
    defaultName: "Hammer Curl",
    category: "arms",
    primaryMuscles: ["biceps", "brachialis"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-tricep-pushdown",
    slug: "tricep-pushdown",
    defaultName: "Tricep Pushdown",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
  },
  {
    id: "ex-overhead-tricep-extension",
    slug: "oh-tricep-ext",
    defaultName: "Overhead Tricep Extension",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable"],
  },
  {
    id: "ex-ab-wheel-rollout",
    slug: "ab-wheel",
    defaultName: "Ab Wheel Rollout",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["ab wheel"],
  },
  {
    id: "ex-cable-crunch",
    slug: "cable-crunch",
    defaultName: "Cable Crunch",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
  },
  {
    id: "ex-hanging-leg-raise",
    slug: "hanging-leg-raise",
    defaultName: "Hanging Leg Raise",
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["pull-up bar"],
  },
  {
    id: "ex-barbell-glute-bridge",
    slug: "bb-glute-bridge",
    defaultName: "Barbell Glute Bridge",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell"],
  },
  {
    id: "ex-hip-thrust",
    slug: "hip-thrust",
    defaultName: "Hip Thrust",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-seated-leg-curl",
    slug: "seated-leg-curl",
    defaultName: "Seated Leg Curl",
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-good-morning",
    slug: "good-morning",
    defaultName: "Good Morning",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "lower back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-stiff-legged-deadlift",
    slug: "sldl",
    defaultName: "Stiff-Legged Deadlift",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "lower back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-sumo-deadlift",
    slug: "sumo-deadlift",
    defaultName: "Sumo Deadlift",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["quads", "lower back"],
    equipment: ["barbell"],
  },
  {
    id: "ex-concentration-curl",
    slug: "concentration-curl",
    defaultName: "Concentration Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
  },
  {
    id: "ex-preacher-curl",
    slug: "preacher-curl",
    defaultName: "Preacher Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "preacher bench"],
  },
  {
    id: "ex-incline-bicep-curl",
    slug: "incline-bicep-curl",
    defaultName: "Incline Dumbbell Curl",
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-dumbbell-tricep-kickback",
    slug: "db-tricep-kickback",
    defaultName: "Dumbbell Tricep Kickback",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-skullcrusher",
    slug: "skullcrusher",
    defaultName: "Skullcrusher",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-cable-lateral-raise",
    slug: "cable-lateral",
    defaultName: "Cable Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
  },
  {
    id: "ex-arnold-press",
    slug: "arnold-press",
    defaultName: "Arnold Press",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-dumbbell-rear-delt-row",
    slug: "db-rear-delt-row",
    defaultName: "Dumbbell Rear Delt Row",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["traps", "lats"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-cable-rear-delt-fly",
    slug: "cable-rear-delt",
    defaultName: "Cable Rear Delt Fly",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["traps"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-pec-deck",
    slug: "pec-deck",
    defaultName: "Pec Deck Fly",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["machine"],
  },
  {
    id: "ex-cable-fly",
    slug: "cable-fly",
    defaultName: "Cable Fly",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-dumbbell-fly",
    slug: "db-fly",
    defaultName: "Dumbbell Fly",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-incline-db-fly",
    slug: "incline-db-fly",
    defaultName: "Incline Dumbbell Fly",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-cable-cross-over",
    slug: "cable-crossover",
    defaultName: "Cable Cross Over",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-squat-jump",
    slug: "squat-jump",
    defaultName: "Bodyweight Squat Jump",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bodyweight"],
  },
  {
    id: "ex-calf-raise",
    slug: "calf-raise",
    defaultName: "Standing Calf Raise",
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine", "bodyweight"],
  },
  {
    id: "ex-seated-calf-raise",
    slug: "seated-calf-raise",
    defaultName: "Seated Calf Raise",
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-farmer-carry",
    slug: "farmer-carry",
    defaultName: "Farmer Carry",
    category: "full-body",
    primaryMuscles: ["forearms", "grip", "core"],
    secondaryMuscles: ["legs", "shoulders"],
    equipment: ["dumbbells", "barbells"],
  },
  {
    id: "ex-kettlebell-swing",
    slug: "kettlebell-swing",
    defaultName: "Kettlebell Swing",
    category: "posterior-chain",
    primaryMuscles: ["glutes", "hamstrings", "lower back"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-cable-woodchopper",
    slug: "cable-woodchopper",
    defaultName: "Cable Woodchopper",
    category: "core",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs", "shoulders"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-barbell-hip-thrust",
    slug: "bb-hip-thrust",
    defaultName: "Barbell Hip Thrust",
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-dumbbell-step-up",
    slug: "db-step-up",
    defaultName: "Dumbbell Step-Up",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["dumbbells", "box"],
  },
  {
    id: "ex-cable-lat-raise",
    slug: "cable-lat-raise",
    defaultName: "Cable Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["delts"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
  },
  {
    id: "ex-cable-face-pull",
    slug: "face-pull",
    defaultName: "Cable Face Pull",
    category: "shoulders",
    primaryMuscles: ["rear delts"],
    secondaryMuscles: ["traps", "lats"],
    equipment: ["cable machine"],
  },
  {
    id: "ex-barbell-deadstop-row",
    slug: "deadstop-row",
    defaultName: "Barbell Deadstop Row",
    category: "pull",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps", "traps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-barbell-goodmorning",
    slug: "bb-goodmorning",
    defaultName: "Barbell Good Morning",
    category: "posterior-chain",
    primaryMuscles: ["hamstrings", "lower back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-standing-overhead-cable-tricep",
    slug: "oh-cable-tricep",
    defaultName: "Standing Overhead Cable Tricep Extension",
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
  },
  {
    id: "ex-dumbbell-lateral-lunge",
    slug: "db-lateral-lunge",
    defaultName: "Dumbbell Lateral Lunge",
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "adductors"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-barbell-shrug-behind",
    slug: "bb-shrug-behind",
    defaultName: "Barbell Behind-the-Back Shrug",
    category: "shoulders",
    primaryMuscles: ["traps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-machine-row",
    slug: "machine-row",
    defaultName: "Machine Row",
    category: "pull",
    primaryMuscles: ["lats", "rear delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["machine"],
  },
  {
    id: "ex-machine-chest-press",
    slug: "machine-chest-press",
    defaultName: "Machine Chest Press",
    category: "chest",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["machine"],
  },
  {
    id: "ex-incline-cable-fly",
    slug: "incline-cable-fly",
    defaultName: "Incline Cable Fly",
    category: "chest",
    primaryMuscles: ["upper chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine", "bench"],
  },
  {
    id: "ex-low-cable-crossover",
    slug: "low-cable-crossover",
    defaultName: "Low Cable Crossover",
    category: "chest",
    primaryMuscles: ["lower chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["cable machine"],
  },
];

export const dummySessionLayout: SessionLayoutItem[] = [
  {
    type: "exercise",
    id: "item-1",
    exercise: {
      id: "session-ex-1",
      exerciseInfoId: "ex-bench-press",
      name: "Barbell Bench Press",
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["barbell", "bench"],
      sets: [
        { id: "set-1", reps: 8, weight: 80, isCompleted: true },
        { id: "set-2", reps: 8, weight: 85, isCompleted: false },
      ],
    },
  },
  {
    type: "exercise",
    id: "item-2",
    exercise: {
      id: "session-ex-2",
      exerciseInfoId: "ex-shoulder-press",
      name: "Overhead Press",
      primaryMuscles: ["delts"],
      secondaryMuscles: ["triceps"],
      equipment: ["barbell"],
      sets: [
        { id: "set-3", reps: 10, weight: 50 },
        { id: "set-4", reps: 10, weight: 50 },
      ],
    },
  },
  {
    type: "exercise",
    id: "item-3",
    exercise: {
      id: "session-ex-3",
      exerciseInfoId: "ex-pullups",
      name: "Pull-Ups",
      primaryMuscles: ["lats"],
      secondaryMuscles: ["biceps"],
      equipment: ["bodyweight"],
      sets: [
        { id: "set-5", reps: 8, weight: 0 },
        { id: "set-6", reps: 7, weight: 0 },
      ],
    },
  },
  {
    type: "exercise",
    id: "item-4",
    exercise: {
      id: "session-ex-4",
      exerciseInfoId: "ex-squat",
      name: "Barbell Back Squat",
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core"],
      equipment: ["barbell", "rack"],
      sets: [{ id: "set-7", reps: 5, weight: 100 }],
    },
  },
  {
    type: "exercise",
    id: "item-5",
    exercise: {
      id: "session-ex-5",
      exerciseInfoId: "ex-deadlift",
      name: "Conventional Deadlift",
      primaryMuscles: ["hamstrings", "glutes"],
      secondaryMuscles: ["lower back", "traps"],
      equipment: ["barbell"],
      sets: [{ id: "set-8", reps: 5, weight: 120 }],
    },
  },
];
