import { ExerciseInfo } from "../../stores/workout/types";

export const exercisesDefList: ExerciseInfo[] = [
  {
    id: "ex-bench-press",
    defaultName: { en: "Barbell Bench Press", rs: "Barbell Bench Press" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["triceps", "front-delts", "side-delts"],
    equipment: ["barbell", "bench"],
    metadata: {
      tips: [
        {
          id: "bench-setup",
          title: "Lock your base",
          tip: "Plant your feet and pin your upper back to the bench before unracking.",
        },
        {
          id: "bench-bar-path",
          title: "Bar path",
          tip: "Lower to mid-chest and press slightly back, not straight up.",
        },
      ],
    },
  },
  {
    id: "ex-back-squat",
    defaultName: { en: "Barbell Back Squat", rs: "Barbell Back Squat" },
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "rack"],
    metadata: {
      tips: [
        {
          id: "squat-brace",
          title: "Brace first",
          tip: "Take a deep breath and brace your core before every rep.",
        },
        {
          id: "squat-depth",
          title: "Own the bottom",
          tip: "Control the descent and stay tight coming out of the hole.",
        },
      ],
    },
  },
  {
    id: "ex-deadlift",
    defaultName: { en: "Conventional Deadlift", rs: "Conventional Deadlift" },
    category: "back",
    primaryMuscles: ["hamstrings", "glutes", "lower-back"],
    secondaryMuscles: ["mid-traps", "forearms"],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "deadlift-slack",
          title: "Pull the slack",
          tip: "Create tension in the bar before you lift it off the floor.",
        },
        {
          id: "deadlift-bar",
          title: "Bar stays close",
          tip: "Keep the bar glued to your shins to protect your lower back.",
        },
      ],
    },
  },
  {
    id: "ex-ohp",
    defaultName: { en: "Overhead Press", rs: "Overhead Press" },
    category: "shoulders",
    primaryMuscles: ["front-delts", "side-delts"],
    secondaryMuscles: ["triceps", "rear-delts"],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "ohp-stack",
          title: "Stay stacked",
          tip: "Squeeze glutes and ribs down to avoid leaning back.",
        },
      ],
    },
  },
  {
    id: "ex-pullups",
    defaultName: { en: "Pull Up", rs: "Pull Up" },
    category: "back",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "rear-delts"],
    equipment: ["bodyweight", "pull-up-bar"],
    metadata: {
      tips: [
        {
          id: "pullup-start",
          title: "Dead hang",
          tip: "Start each rep from a controlled dead hang, no bounce.",
        },
        {
          id: "pullup-cue",
          title: "Chest to bar",
          tip: "Think chest to bar instead of chin over bar.",
        },
      ],
    },
  },
  {
    id: "ex-incline-bench",
    defaultName: {
      en: "Incline Barbell Bench Press",
      rs: "Incline Barbell Bench Press",
    },
    category: "chest",
    primaryMuscles: ["upper-chest"],
    secondaryMuscles: ["triceps", "front-delts"],
    equipment: ["barbell", "bench"],
    metadata: {
      tips: [
        {
          id: "incline-angle",
          title: "Bench angle",
          tip: "Use a moderate incline to keep tension on upper chest.",
        },
      ],
    },
  },
  {
    id: "ex-decline-bench",
    defaultName: {
      en: "Decline Barbell Bench Press",
      rs: "Decline Barbell Bench Press",
    },
    category: "chest",
    primaryMuscles: ["lower-chest"],
    secondaryMuscles: ["triceps", "front-delts"],
    equipment: ["barbell", "bench"],
    metadata: {
      tips: [
        {
          id: "decline-control",
          title: "Stay controlled",
          tip: "Lower the bar slowly to keep shoulders safe.",
        },
      ],
    },
  },
  {
    id: "ex-db-bench",
    defaultName: { en: "Dumbbell Bench Press", rs: "Dumbbell Bench Press" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["triceps", "front-delts", "side-delts"],
    equipment: ["dumbbells", "bench"],
    metadata: {
      tips: [
        {
          id: "db-bench-path",
          title: "Natural path",
          tip: "Let dumbbells move slightly inward as you press.",
        },
      ],
    },
  },
  {
    id: "ex-db-incline",
    defaultName: { en: "Incline Dumbbell Press", rs: "Incline Dumbbell Press" },
    category: "chest",
    primaryMuscles: ["upper-chest"],
    secondaryMuscles: ["triceps", "front-delts", "side-delts"],
    equipment: ["dumbbells", "bench"],
    metadata: {
      tips: [
        {
          id: "db-incline-depth",
          title: "Deep stretch",
          tip: "Lower until you feel a controlled stretch in upper chest.",
        },
      ],
    },
  },
  {
    id: "ex-dips",
    defaultName: { en: "Weighted Dips", rs: "Weighted Dips" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["triceps", "front-delts"],
    equipment: ["bodyweight", "dip-bar"],
    metadata: {
      tips: [
        {
          id: "dip-lean",
          title: "Lean forward",
          tip: "Slight forward lean shifts tension to the chest.",
        },
      ],
    },
  },
  {
    id: "ex-leg-press",
    defaultName: { en: "Leg Press", rs: "Leg Press" },
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    metadata: {
      tips: [
        {
          id: "legpress-depth",
          title: "Depth matters",
          tip: "Lower until thighs approach chest without lifting hips.",
        },
      ],
    },
  },
  {
    id: "ex-leg-ext",
    defaultName: { en: "Leg Extension", rs: "Leg Extension" },
    category: "legs",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["machine"],
    metadata: {
      tips: [
        {
          id: "legext-squeeze",
          title: "Top squeeze",
          tip: "Pause briefly at the top and squeeze the quads.",
        },
      ],
    },
  },
  {
    id: "ex-leg-curl",
    defaultName: { en: "Leg Curl", rs: "Leg Curl" },
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
    metadata: {
      tips: [
        {
          id: "legcurl-control",
          title: "Slow negatives",
          tip: "Control the eccentric to maximize hamstring tension.",
        },
      ],
    },
  },
  {
    id: "ex-barbell-lunge",
    defaultName: { en: "Barbell Lunge", rs: "Barbell Lunge" },
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "lunge-balance",
          title: "Stay balanced",
          tip: "Keep torso upright and step far enough forward.",
        },
      ],
    },
  },
  {
    id: "ex-rdl",
    defaultName: { en: "Romanian Deadlift", rs: "Romanian Deadlift" },
    category: "back",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back"],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "rdl-hips",
          title: "Hips back",
          tip: "Push hips back and keep shins nearly vertical.",
        },
      ],
    },
  },
  {
    id: "ex-barbell-row",
    defaultName: { en: "Barbell Bent-Over Row", rs: "Barbell Bent-Over Row" },
    category: "back",
    primaryMuscles: ["lats", "rear-delts"],
    secondaryMuscles: ["biceps", "mid-traps"],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "row-torso",
          title: "Stable torso",
          tip: "Keep your torso angle fixed throughout the set.",
        },
      ],
    },
  },
  {
    id: "ex-1arm-db-row",
    defaultName: { en: "One-Arm Dumbbell Row", rs: "One-Arm Dumbbell Row" },
    category: "back",
    primaryMuscles: ["lats", "rear-delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbells", "bench"],
    metadata: {
      tips: [
        {
          id: "db-row-pull",
          title: "Elbow path",
          tip: "Pull elbow toward your hip, not straight up.",
        },
      ],
    },
  },
  {
    id: "ex-lat-pulldown",
    defaultName: { en: "Lat Pulldown", rs: "Lat Pulldown" },
    category: "back",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    metadata: {
      tips: [
        {
          id: "pulldown-start",
          title: "Lead with elbows",
          tip: "Drive elbows down before bending the arms.",
        },
      ],
    },
  },
  {
    id: "ex-cable-row",
    defaultName: { en: "Seated Cable Row", rs: "Seated Cable Row" },
    category: "back",
    primaryMuscles: ["lats", "rear-delts"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    metadata: {
      tips: [
        {
          id: "cable-row-chest",
          title: "Chest up",
          tip: "Keep chest tall and avoid rounding the back.",
        },
      ],
    },
  },
  {
    id: "ex-barbell-shrug",
    defaultName: { en: "Barbell Shrug", rs: "Barbell Shrug" },
    category: "shoulders",
    primaryMuscles: ["upper-traps", "mid-traps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    metadata: {
      tips: [
        {
          id: "shrug-up",
          title: "Straight up",
          tip: "Lift shoulders straight up, not rolling them.",
        },
      ],
    },
  },
  {
    id: "ex-lateral-raise",
    defaultName: { en: "Dumbbell Lateral Raise", rs: "Dumbbell Lateral Raise" },
    category: "shoulders",
    primaryMuscles: ["side-delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-front-raise",
    defaultName: { en: "Front Dumbbell Raise", rs: "Front Dumbbell Raise" },
    category: "shoulders",
    primaryMuscles: ["front-delts"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-rear-delt-fly",
    defaultName: { en: "Rear Delt Fly", rs: "Rear Delt Fly" },
    category: "shoulders",
    primaryMuscles: ["rear-delts"],
    secondaryMuscles: ["mid-traps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-barbell-curl",
    defaultName: { en: "Barbell Bicep Curl", rs: "Barbell Bicep Curl" },
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
  },
  {
    id: "ex-hammer-curl",
    defaultName: { en: "Hammer Curl", rs: "Hammer Curl" },
    category: "arms",
    primaryMuscles: ["biceps", "brachialis", "triceps", "forearms"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-tricep-pushdown",
    defaultName: { en: "Tricep Pushdown", rs: "Tricep Pushdown" },
    category: "arms",
    primaryMuscles: ["triceps", "forearms"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-oh-tricep-ext",
    defaultName: {
      en: "Overhead Tricep Extension",
      rs: "Overhead Tricep Extension",
    },
    category: "arms",
    primaryMuscles: ["triceps", "forearms"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "cable"],
  },
  {
    id: "ex-other",
    defaultName: { en: "Ab Wheel Rollout", rs: "Ab Wheel Rollout" },
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["other"],
  },
  {
    id: "ex-cable-crunch",
    defaultName: { en: "Cable Crunch", rs: "Cable Crunch" },
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-hanging-leg-raise",
    defaultName: { en: "Hanging Leg Raise", rs: "Hanging Leg Raise" },
    category: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip-flexors"],
    equipment: ["pull-up-bar"],
  },
  {
    id: "ex-bb-glute-bridge",
    defaultName: { en: "Barbell Glute Bridge", rs: "Barbell Glute Bridge" },
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell"],
  },
  {
    id: "ex-hip-thrust",
    defaultName: { en: "Hip Thrust", rs: "Hip Thrust" },
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-seated-leg-curl",
    defaultName: { en: "Seated Leg Curl", rs: "Seated Leg Curl" },
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-good-morning",
    defaultName: { en: "Good Morning", rs: "Good Morning" },
    category: "back",
    primaryMuscles: ["hamstrings", "lower-back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-sldl",
    defaultName: { en: "Stiff-Legged Deadlift", rs: "Stiff-Legged Deadlift" },
    category: "back",
    primaryMuscles: ["hamstrings", "lower-back"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-sumo-deadlift",
    defaultName: { en: "Sumo Deadlift", rs: "Sumo Deadlift" },
    category: "back",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["quads", "lower-back"],
    equipment: ["barbell"],
  },
  {
    id: "ex-concentration-curl",
    defaultName: { en: "Concentration Curl", rs: "Concentration Curl" },
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
  },
  {
    id: "ex-preacher-curl",
    defaultName: { en: "Preacher Curl", rs: "Preacher Curl" },
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "other"],
  },
  {
    id: "ex-incline-bicep-curl",
    defaultName: { en: "Incline Dumbbell Curl", rs: "Incline Dumbbell Curl" },
    category: "arms",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-db-tricep-kickback",
    defaultName: {
      en: "Dumbbell Tricep Kickback",
      rs: "Dumbbell Tricep Kickback",
    },
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-skullcrusher",
    defaultName: { en: "Skullcrusher", rs: "Skullcrusher" },
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-cable-lateral",
    defaultName: { en: "Cable Lateral Raise", rs: "Cable Lateral Raise" },
    category: "shoulders",
    primaryMuscles: ["side-delts"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-arnold-press",
    defaultName: { en: "Arnold Press", rs: "Arnold Press" },
    category: "shoulders",
    primaryMuscles: ["front-delts", "side-delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-db-rear-delt-row",
    defaultName: { en: "Dumbbell Rear Delt Row", rs: "Dumbbell Rear Delt Row" },
    category: "shoulders",
    primaryMuscles: ["rear-delts"],
    secondaryMuscles: ["mid-traps", "lats"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-cable-rear-delt",
    defaultName: { en: "Cable Rear Delt Fly", rs: "Cable Rear Delt Fly" },
    category: "shoulders",
    primaryMuscles: ["rear-delts"],
    secondaryMuscles: ["mid-traps"],
    equipment: ["cable"],
  },
  {
    id: "ex-pec-deck",
    defaultName: { en: "Pec Deck Fly", rs: "Pec Deck Fly" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["machine"],
  },
  {
    id: "ex-cable-fly",
    defaultName: { en: "Cable Fly", rs: "Cable Fly" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-db-fly",
    defaultName: { en: "Dumbbell Fly", rs: "Dumbbell Fly" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-incline-db-fly",
    defaultName: { en: "Incline Dumbbell Fly", rs: "Incline Dumbbell Fly" },
    category: "chest",
    primaryMuscles: ["upper-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["dumbbells", "bench"],
  },
  {
    id: "ex-cable-crossover",
    defaultName: { en: "Cable Cross Over", rs: "Cable Cross Over" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-squat-jump",
    defaultName: { en: "Bodyweight Squat Jump", rs: "Bodyweight Squat Jump" },
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bodyweight"],
  },
  {
    id: "ex-calf-raise",
    defaultName: { en: "Standing Calf Raise", rs: "Standing Calf Raise" },
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine", "bodyweight"],
  },
  {
    id: "ex-seated-calf-raise",
    defaultName: { en: "Seated Calf Raise", rs: "Seated Calf Raise" },
    category: "legs",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
  },
  {
    id: "ex-farmer-carry",
    defaultName: { en: "Farmer Carry", rs: "Farmer Carry" },
    category: "full-body",
    primaryMuscles: ["forearms", "grip", "core"],
    secondaryMuscles: ["legs", "front-delts", "side-delts"],
    equipment: ["dumbbells", "barbells"],
  },
  {
    id: "ex-kettlebell-swing",
    defaultName: { en: "Kettlebell Swing", rs: "Kettlebell Swing" },
    category: "full-body",
    primaryMuscles: ["glutes", "hamstrings", "lower-back"],
    secondaryMuscles: ["side-delts", "front-delts", "core"],
    equipment: ["kettlebell"],
  },
  {
    id: "ex-cable-woodchopper",
    defaultName: { en: "Cable Woodchopper", rs: "Cable Woodchopper" },
    category: "core",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs", "side-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-bb-hip-thrust",
    defaultName: { en: "Barbell Hip Thrust", rs: "Barbell Hip Thrust" },
    category: "legs",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "bench"],
  },
  {
    id: "ex-db-step-up",
    defaultName: { en: "Dumbbell Step-Up", rs: "Dumbbell Step-Up" },
    category: "legs",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["dumbbells", "other"],
  },
  {
    id: "ex-cable-lat-raise",
    defaultName: { en: "Cable Lateral Raise", rs: "Cable Lateral Raise" },
    category: "shoulders",
    primaryMuscles: ["side-delts"],
    secondaryMuscles: ["front-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-face-pull",
    defaultName: { en: "Cable Face Pull", rs: "Cable Face Pull" },
    category: "back",
    primaryMuscles: ["rear-delts", "mid-traps"],
    secondaryMuscles: ["lats", "side-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-deadstop-row",
    defaultName: { en: "Barbell Deadstop Row", rs: "Barbell Deadstop Row" },
    category: "back",
    primaryMuscles: ["lats", "mid-traps"],
    secondaryMuscles: ["rear-delts", "biceps"],
    equipment: ["barbell", "rack"],
  },
  {
    id: "ex-bb-goodmorning",
    defaultName: { en: "Barbell Good Morning", rs: "Barbell Good Morning" },
    category: "back",
    primaryMuscles: ["lower-back", "hamstrings"],
    secondaryMuscles: ["glutes"],
    equipment: ["barbell"],
  },
  {
    id: "ex-oh-cable-tricep",
    defaultName: {
      en: "Standing Overhead Cable Tricep Extension",
      rs: "Standing Overhead Cable Tricep Extension",
    },
    category: "arms",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
  },
  {
    id: "ex-db-lateral-lunge",
    defaultName: {
      en: "Dumbbell Lateral Lunge",
      rs: "Dumbbell Lateral Lunge",
    },
    category: "legs",
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbells"],
  },
  {
    id: "ex-bb-shrug-behind",
    defaultName: {
      en: "Barbell Behind-the-Back Shrug",
      rs: "Barbell Behind-the-Back Shrug",
    },
    category: "back",
    primaryMuscles: ["upper-traps"],
    secondaryMuscles: ["mid-traps"],
    equipment: ["barbell"],
  },
  {
    id: "ex-machine-row",
    defaultName: { en: "Machine Row", rs: "Machine Row" },
    category: "back",
    primaryMuscles: ["lats", "mid-traps"],
    secondaryMuscles: ["rear-delts", "biceps"],
    equipment: ["machine"],
  },
  {
    id: "ex-machine-chest-press",
    defaultName: { en: "Machine Chest Press", rs: "Machine Chest Press" },
    category: "chest",
    primaryMuscles: ["mid-chest"],
    secondaryMuscles: ["front-delts", "triceps"],
    equipment: ["machine"],
  },
  {
    id: "ex-incline-cable-fly",
    defaultName: { en: "Incline Cable Fly", rs: "Incline Cable Fly" },
    category: "chest",
    primaryMuscles: ["upper-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["cable"],
  },
  {
    id: "ex-low-cable-crossover",
    defaultName: { en: "Low Cable Crossover", rs: "Low Cable Crossover" },
    category: "chest",
    primaryMuscles: ["lower-chest"],
    secondaryMuscles: ["front-delts", "side-delts"],
    equipment: ["cable"],
  },
];
