export const fixedMuscleOrder = [
  "chest",
  "upper-chest",
  "mid-chest",
  "lower-chest",
  "shoulders",
  "front-delts",
  "side-delts",
  "rear-delts",
  "back",
  "lats",
  "lower-back",
  "upper-traps",
  "mid-traps",
  "arms",
  "biceps",
  "brachialis",
  "triceps",
  "forearms",
  "legs",
  "quads",
  "hamstrings",
  "glutes",
  "calves",
  "adductors",
  "core",
  "abs",
  "obliques",
  "hip-flexors",
  "full-body",
  "grip",
];

export const CATEGORY_RULES: Record<
  string,
  { primary: string[]; secondary: string[] }
> = {
  "full-body": { primary: ["full-body"], secondary: ["full-body"] },
  chest: { primary: ["chest"], secondary: ["chest", "shoulders", "arms"] },
  back: { primary: ["back"], secondary: ["back", "arms", "shoulders"] },
  shoulders: { primary: ["shoulders"], secondary: ["shoulders", "arms"] },
  arms: { primary: ["arms"], secondary: ["arms"] },
  legs: { primary: ["legs"], secondary: ["legs", "core"] },
  core: { primary: ["core"], secondary: ["shoulders", "legs", "core"] },
};
